const fs = require('fs');
fs.mkdirSync('src/app/api/ai-reply', { recursive: true });
const lines = [
"import { NextRequest, NextResponse } from 'next/server'",
"",
"export async function POST(req: NextRequest) {",
"  try {",
"    const { message } = await req.json()",
"",
"    const isNepali = /[a-z]/i.test(message) && ['ko','cha','ho','bhai','dai','kati','kahile','xa','hunxa','dinus','milxa','garnu'].some(w => message.toLowerCase().includes(w))",
"    const isEnglish = !isNepali",
"    const isMixed = isNepali && /[a-zA-Z]{4,}/.test(message)",
"",
"    let langInstruction = 'Reply in Romanized Nepali (e.g. Namaste! Tapaaiko...) friendly tone'",
"    if (isEnglish) langInstruction = 'Reply in English, friendly and professional tone'",
"    if (isMixed) langInstruction = 'Reply in mixed Nepali-English (like: Namaste! Your order is confirmed xa), friendly tone'",
"",
"    const response = await fetch('https://api.anthropic.com/v1/messages', {",
"      method: 'POST',",
"      headers: {",
"        'Content-Type': 'application/json',",
"        'x-api-key': process.env.ANTHROPIC_API_KEY || '',",
"        'anthropic-version': '2023-06-01'",
"      },",
"      body: JSON.stringify({",
"        model: 'claude-sonnet-4-20250514',",
"        max_tokens: 200,",
"        messages: [{",
"          role: 'user',",
"          content: `You are a helpful customer service assistant for OlkoCMS, a Nepali e-commerce store. ${langInstruction}. Keep reply short (2-3 sentences max), helpful and friendly. Customer message: ${message}`",
"        }]",
"      })",
"    })",
"",
"    const data = await response.json()",
"    const reply = data.content?.[0]?.text || 'Sorry, could not generate reply.'",
"    return NextResponse.json({ reply })",
"  } catch (error) {",
"    return NextResponse.json({ error: 'Failed to generate reply' }, { status: 500 })",
"  }",
"}",
].join('\n');
fs.writeFileSync('src/app/api/ai-reply/route.ts', lines, 'utf8');
console.log('Real AI Reply API done!');